package com.offerflow.copilot.security.local;

public enum PermissionAction {
    REVIEW_CONFIRM,
    REVIEW_RETURN,
    REVIEW_FLAG_RISK,
    EVIDENCE_CREATE,
    EVIDENCE_UPDATE,
    EVIDENCE_CONFIRM,
    EVIDENCE_ARCHIVE,
    EVIDENCE_RESTORE,
    JD_CREATE,
    JD_UPDATE,
    JD_PARSE,
    JD_BIND_EVIDENCE,
    MATCH_REPORT_GENERATE,
    MATCH_REPORT_SEND_TO_REVIEW,
    MATCH_REPORT_ARCHIVE,
    MATCH_REPORT_RESTORE,
    COPY_CHECK,
    PROVIDER_SANDBOX_RUN
}
